spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ds3_armor_calc?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 23Appleswordfish!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      data-source-properties:
        allowPublicKeyRetrieval: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect
